name: Build EC2
on: [workflow_dispatch]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ec2-184-73-30-8.compute-1.amazonaws.com >> ~/.ssh/known_hosts

      - name: SSH into EC2 Instance and Check Hostname
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@ec2-184-73-30-8.compute-1.amazonaws.com "hostname"
    
