name: Build and Push Docker Image to ECR
on: [workflow_dispatch]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ec2-184-73-30-8.compute-1.amazonaws.com
          REMOTE_USER: ec2-user
    run: | 
      hostname

    
