name: Build and Deploy to EKS

on:
  push:
    branches:
      - eks

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: 201135917397.dkr.ecr.us-east-2.amazonaws.com/demo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY:$IMAGE_TAG .
          docker push $ECR_REGISTRY:$IMAGE_TAG
          echo "::set-output name=image-uri::$ECR_REGISTRY:$IMAGE_TAG"

      - name: Install and Configure kubectl
        run: |
          echo "Installing kubectl..."
          sudo apt-get update && sudo apt-get install -y apt-transport-https
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install -y kubectl

      - name: Deploy to EKS
        env:
          K8S_NAMESPACE: default 
          K8S_DEPLOYMENT_NAME: sample
          IMAGE_URI: ${{ steps.build-and-push.outputs.image-uri }}
        run: |
          # aws eks update-kubeconfig --region us-east-2 --name eks-demo
          # kubectl config use-context eks-demo
          # kubectl set image deployment/${K8S_DEPLOYMENT_NAME} ${K8S_DEPLOYMENT_NAME}=${IMAGE_URI} -n ${K8S_NAMESPACE}
          cat deployment.yaml
      - name: Update Kubernetes Deployment YAML
        env:
          IMAGE_URI: ${{ env.IMAGE_URI }}
          ECR_REGISTRY: 201135917397.dkr.ecr.us-east-2.amazonaws.com/demo
        run: |
            sed -i "s|image:.*|image: $ECR_REGISTRY/your-app-name:$GITHUB_SHA|" deployment.yaml
            cat deployment.yaml
            #ws eks update-kubeconfig --region us-east-2 --name eks-demo