name: Build EC2
on: [workflow_dispatch]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
    
      - name: Connect to EC2 and Check Hostname
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_PUBLIC_IP: YOUR_EC2_PUBLIC_IP  # Replace with your EC2's public IP
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          ssh -i private_key.pem ec2-user@ec2-184-73-30-8.compute-1.amazonaws.com 'hostname'
    
