name: Build EC2
on: [workflow_dispatch]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
    
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change this to your desired region

      - name: SSH into EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-184-73-30-8.compute-1.amazonaws.com "hostname"
        continue-on-error: true  # Continue even if the command fails
    
