name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::201135917397:role/test
        aws-region: us-east-1
    - name: Copy files to the test website with the AWS CLI
      run: |
        aws iam list-users
