name: My Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract variables
      run: |

        output=$(python prepare_new_deployment.py)          
        for var in $(echo $output | tr '=' '\n'); do
          value=$(echo $var | awk -F'[=]' '{print $2}')
          case $(echo $var | awk -F'[=]' '{print $1}') in
            "QA")
              echo "VAR1=$value" >> $GITHUB_ENV
              ;;
            "ABC QA")
              echo "VAR2=$value" >> $GITHUB_ENV
              ;;
            "RW")
              echo "VAR3=$value" >> $GITHUB_ENV
              ;;
            "T-PR")
              echo "VAR4=$value" >> $GITHUB_ENV
              ;;
            "1.0")
              echo "VAR5=$value" >> $GITHUB_ENV
              ;;
            "77276535")
              echo "VAR6=$value" >> $GITHUB_ENV
              ;;
            "20230218-235959")
              echo "VAR7=$value" >> $GITHUB_ENV
              ;;
            "abc5.com")
              echo "VAR8=$value" >> $GITHUB_ENV
              ;;
          esac
        done
