name: My Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract variables
      run: |
        output=$(python prepare_new_deployment.py)          
        VAR1=$(echo $output | cut -d '=' -f 1 | awk '{print $1}')
        VAR2=$(echo $output | cut -d '=' -f 2 | awk '{print $1}')
        VAR3=$(echo $output | cut -d '=' -f 3 | awk '{print $1}')
        VAR4=$(echo $output | cut -d '=' -f 4 | awk '{print $1}')
        VAR5=$(echo $output | cut -d '=' -f 5 | awk '{print $1}')
        VAR6=$(echo $output | cut -d '=' -f 6 | awk '{print $1}')
        VAR7=$(echo $output | cut -d '=' -f 7 | awk '{print $1}')
        VAR8=abc5.com
        echo "VAR1=$VAR1" >> $GITHUB_ENV
        echo "VAR2=$VAR2" >> $GITHUB_ENV
        echo "VAR3=$VAR3" >> $GITHUB_ENV
        echo "VAR4=$VAR4" >> $GITHUB_ENV
        echo "VAR5=$VAR5" >> $GITHUB_ENV
        echo "VAR6=$VAR6" >> $GITHUB_ENV
        echo "VAR7=$VAR7" >> $GITHUB_ENV
        echo "VAR8=$VAR8" >> $GITHUB_ENV