name: My Workflow

on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script
        run: |
          output=$(python prepare_new_deployment.py)
          echo "::set-output name=environment::$(echo "$output" | awk -F ': ' '/ENVironment:/ {print $2}')"
          echo "::set-output name=deployment_context::$(echo "$output" | awk -F ': ' '/DEPLOYMENT_CONTEXT:/ {print $2}')"
          echo "::set-output name=model_names::$(echo "$output" | awk -F ': ' '/MODEL_NAMES:/ {print $2}')"
          echo "::set-output name=model_versions::$(echo "$output" | awk -F ': ' '/MODEL_VERSIONS:/ {print $2}')"
          echo "::set-output name=system_uids::$(echo "$output" | awk -F ': ' '/SYSTEM_UIDS:/ {print $2}')"
          echo "::set-output name=testing_times::$(echo "$output" | awk -F ': ' '/TESTING_TIMES:/ {print $2}')"

      - name: Use output variables
        run: |
          echo "Environment: ${{ steps.my_job.outputs.environment }}"
          echo "Deployment context: ${{ steps.my_job.outputs.deployment_context }}"
          echo "Model names: ${{ steps.my_job.outputs.model_names }}"
          echo "Model versions: ${{ steps.my_job.outputs.model_versions }}"
          echo "System UIDs: ${{ steps.my_job.outputs.system_uids }}"
          echo "Testing times: ${{ steps.my_job.outputs.testing_times }}"
