name: My Workflow
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    inputs:
      environment:
        description: 'Environment'
        required: true
      deployment_context:
        description: 'Deployment Context'
        required: true
      model_names:
        description: 'Model Names'
        required: true
      model_versions:
        description: 'Model Versions'
        required: true
      system_uids:
        description: 'System UIDs'
        required: true
      testing_times:
        description: 'Testing Times'
        required: true
    steps:
      - name: My Step
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Deployment Context: ${{ inputs.deployment_context }}"
          echo "Model Names: ${{ inputs.model_names }}"
          echo "Model Versions: ${{ inputs.model_versions }}"
          echo "System UIDs: ${{ inputs.system_uids }}"
          echo "Testing Times: ${{ inputs.testing_times }}"
