name: My Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract variables
      run: |

        python_output=$(python prepare_new_deployment.py)
        environment=$(echo "$python_output" | awk -F": " '/ENVironment/ {print $2}')
        deployment_context=$(echo "$python_output" | awk -F": " '/DEPLOYMENT_CONTEXT/ {print $2}')
        model_names=$(echo "$python_output" | awk -F": " '/MODEL_NAMES/ {print $2}')
        model_versions=$(echo "$python_output" | awk -F": " '/MODEL_VERSIONS/ {print $2}')
        system_uids=$(echo "$python_output" | awk -F": " '/SYSTEM_UIDS/ {print $2}')
        testing_times=$(echo "$python_output" | awk -F": " '/TESTING_TIMES/ {print $2}')

        # Set the environment variables in the GitHub Actions environment
        echo "ENVironment=$environment" >> $GITHUB_ENV
        echo "DEPLOYMENT_CONTEXT=$deployment_context" >> $GITHUB_ENV
        echo "MODEL_NAMES=$model_names" >> $GITHUB_ENV
        echo "MODEL_VERSIONS=$model_versions" >> $GITHUB_ENV
        echo "SYSTEM_UIDS=$system_uids" >> $GITHUB_ENV
        echo "TESTING_TIMES=$testing_times" >> $GITHUB_ENV

    - name: Display environment variables
      run: |
        echo "ENVIRONMENT=${{ env.ENVIRONMENT }}"
        echo "DEPLOYMENT_CONTEXT=${{ env.DEPLOYMENT_CONTEXT }}"
        echo "MODEL_NAMES=${{ env.MODEL_NAMES }}"
        echo "MODEL_VERSIONS=${{ env.MODEL_VERSIONS }}"
        echo "SYSTEM_UIDS=${{ env.SYSTEM_UIDS }}"
        echo "TESTING_TIMES=${{ env.TESTING_TIMES }}"

    - name: Use 
      env : 
        ENVIRONMENT=${{ env.ENVIRONMENT }}
      run: |
        if [[ $ENVIRONMENT =~ "INT" ]]; then
          echo "INT models present; Authenticating for SI"
          # Add authentication steps for SI INT
        else
          echo "No INT models present; hence not authenticating for SI"
        fi

        if [[ $ENVIRONMENT =~ "QA" ]]; then
          echo "QA models present; Authenticating for SI"
          # Add authentication steps for SI QA
        else
          echo "No QA models present; hence not authenticating for SI"
        fi

        if [[ $ENVIRONMENT =~ "PROD" ]]; then
          echo "PROD models present; Authenticating for SI"
          # Add authentication steps for SI PROD
        else
          echo "No PROD models present; hence not authenticating for SI"
        fi

      - name: Run Python script
        run: python script.py --var1 value1 --var2 value2