name: My Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract variables
      run: |
        output=$(python prepare_new_deployment.py)

        environment=$(echo "$output" | grep 'ENVironment:' | awk '{print $2}' | tr -d '[],')
        deployment_context=$(echo "$output" | grep 'DEPLOYMENT_CONTEXT:' | awk '{print $2}' | tr -d '[],')
        model_names=$(echo "$output" | grep 'MODEL_NAMES:' | awk '{print $2}' | tr -d '[],')
        model_versions=$(echo "$output" | grep 'MODEL_VERSIONS:' | awk '{print $2}' | tr -d '[],')
        system_uids=$(echo "$output" | grep 'SYSTEM_UIDS:' | awk '{print $2}' | tr -d '[],')
        testing_times=$(echo "$output" | grep 'TESTING_TIMES:' | awk '{print $2}' | tr -d '[],')

        echo "::set-env name=ENVIRONMENT::$environment"
        echo "::set-env name=DEPLOYMENT_CONTEXT::$deployment_context"
        echo "::set-env name=MODEL_NAMES::$model_names"
        echo "::set-env name=MODEL_VERSIONS::$model_versions"
        echo "::set-env name=SYSTEM_UIDS::$system_uids"
        echo "::set-env name=TESTING_TIMES::$testing_times"


    # - name: Use the outputs
    #   run: |
    #     echo "environment: ${{ steps.build.outputs.environment }}"
    #     echo "deployment_context: ${{ steps.build.outputs.deployment_context }}"
    #     echo "model_names: ${{ steps.build.outputs.model_names }}"
    #     echo "model_versions: ${{ steps.build.outputs.model_versions }}"
    #     echo "system_uids: ${{ steps.build.outputs.system_uids }}"
    #     echo "testing_times: ${{ steps.build.outputs.testing_times }}"
