name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run Python script
        run: python prepare_new_deployment.py.py
        id: python-script
      - name: Extract values
        run: |
          environment=$(echo "${{ steps.python-script.outputs.stdout }}" | grep -oP 'ENVironment: \[\K[^]]+' | tr '\n' ' ')
          deployment_context=$(echo "${{ steps.python-script.outputs.stdout }}" | grep -oP 'DEPLOYMENT_CONTEXT: \[\K[^]]+' | tr '\n' ' ')
          model_names=$(echo "${{ steps.python-script.outputs.stdout }}" | grep -oP 'MODEL_NAMES: \[\K[^]]+' | tr '\n' ' ')
          model_versions=$(echo "${{ steps.python-script.outputs.stdout }}" | grep -oP 'MODEL_VERSIONS: \[\K[^]]+' | tr '\n' ' ')
          system_uids=$(echo "${{ steps.python-script.outputs.stdout }}" | grep -oP 'SYSTEM_UIDS: \[\K[^]]+' | tr '\n' ' ')
          testing_times=$(echo "${{ steps.python-script.outputs.stdout }}" | grep -oP 'TESTING_TIMES: \[\K[^]]+' | tr '\n' ' ')
        id: extract-values
      - name: Set environment variables
        run: |
          echo "ENVIRONMENT=${{ env.environment }}" >> $GITHUB_ENV
          echo "DEPLOYMENT_CONTEXT=${{ env.deployment_context }}" >> $GITHUB_ENV
          echo "MODEL_NAMES=${{ env.model_names }}" >> $GITHUB_ENV
          echo "MODEL_VERSIONS=${{ env.model_versions }}" >> $GITHUB_ENV
          echo "SYSTEM_UIDS=${{ env.system_uids }}" >> $GITHUB_ENV
          echo "TESTING_TIMES=${{ env.testing_times }}" >> $GITHUB_ENV
        env:
          environment: ${{ steps.extract-values.outputs.environment }}
          deployment_context: ${{ steps.extract-values.outputs.deployment_context }}
          model_names: ${{ steps.extract-values.outputs.model_names }}
          model_versions: ${{ steps.extract-values.outputs.model_versions }}
          system_uids: ${{ steps.extract-values.outputs.system_uids }}
          testing_times: ${{ steps.extract-values.outputs.testing_times }}
