name: My Workflow

on: [push]

jobs:
  my_job:
    inputs:
    model: model1
    version: v1
    context: c1
    runs-on: ubuntu-latest
    steps:
      - name: My Step
        run: echo "Hello, world!"
        env:
          MODEL: ${{ inputs.model }}
          VERSION: ${{ inputs.version }}
          CONTEXT: ${{ inputs.context }}
