name: Prepare RE Deployment
on:
  push:
    branches: [ main ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run script
      run: |
        python3 deployment.py > output.txt
        envi=()
        context=()
        model=()
        version=()
        sysuid=()
        testingtime=()
        while read -r line; do
            parts=($(echo "$line" | tr "=" "\n"))
            case 0 in
                "${parts[0]}")
                    envi+=(${parts[1]})
                    ;;
                "${parts[1]}")
                    context+=(${parts[1]})
                    ;;
                "${parts[2]}")
                    model+=(${parts[1]})
                    ;;
                "${parts[3]}")
                    version+=(${parts[1]})
                    ;;
                "${parts[4]}")
                    sysuid+=(${parts[1]})
                    ;;
                "${parts[5]}")
                    testingtime+=(${parts[1]})
                    ;;
            esac
        done < output.txt
        echo "envi=${envi[@]}" >> $GITHUB_ENV
        echo "context=${context[@]}" >> $GITHUB_ENV
        echo "model=${model[@]}" >> $GITHUB_ENV
        echo "version=${version[@]}" >> $GITHUB_ENV
        echo "sysuid=${sysuid[@]}" >> $GITHUB_ENV
        echo "testingtime=${testingtime[@]}" >> $GITHUB_ENV
    - name: Display GitHub Environment Variables
      run: |
       
        if [[ $envi[@] == *"SI INT"* ]]; then
            echo "INT models present; Authenticating for SI"
        else
            echo "No INT models present; hence not authenticating for SI"
        fi

        if [[ $envi[@] == *"SI QA"* ]]; then
            echo "INT models present; Authenticating for SI"
        else
            echo "No INT models present; hence not authenticating for SI"
        fi

        if [[ $envi[@] == *"SI PROD"* ]]; then
            echo "INT models present; Authenticating for SI"
        else
            echo "No INT models present; hence not authenticating for SI"
        fi
    - name: Display GitHub  Variables
      run: |
        if echo "$env" | grep -q "SI INT"; then
            echo "INT models present; Authenticating for SI"
        else
            echo "No INT models present; hence not authenticating for SI"
        fi

        if echo "$env" | grep -q "SI QA"; then
            echo "QA models present; Authenticating for SI"
        else
            echo "No QA models present; hence not authenticating for SI"
        fi

        if echo "$env" | grep -q "SI PROD"; then
            echo "PROD models present; Authenticating for SI"
        else
            echo "No PROD models present; hence not authenticating for SI"
        fi
