name: Prepare RE Deployment
on:
  push:
    branches: [ main ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run script
      run: |
        python3 prepare_re_deployment.py > output.txt
        env=()
        context=()
        model=()
        version=()
        sysuid=()
        testingtime=()
        while read -r line; do
            parts=($(echo "$line" | tr "=" "\n"))
            case 0 in
                "${parts[0]}")
                    env+=(${parts[1]})
                    ;;
                "${parts[1]}")
                    context+=(${parts[1]})
                    ;;
                "${parts[2]}")
                    model+=(${parts[1]})
                    ;;
                "${parts[3]}")
                    version+=(${parts[1]})
                    ;;
                "${parts[4]}")
                    sysuid+=(${parts[1]})
                    ;;
                "${parts[5]}")
                    testingtime+=(${parts[1]})
                    ;;
            esac
        done < output.txt
        echo "env=${env[@]}" >> $GITHUB_ENV
        echo "context=${context[@]}" >> $GITHUB_ENV
        echo "model=${model[@]}" >> $GITHUB_ENV
        echo "version=${version[@]}" >> $GITHUB_ENV
        echo "sysuid=${sysuid[@]}" >> $GITHUB_ENV
        echo "testingtime=${testingtime[@]}" >> $GITHUB_ENV
