name: Store output in environment

on: [push]

jobs:
  read_output:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run script and store output in environment
      run: |
        python3 hs.py
        if 'INT' in os.environ['ENVironment']:
            print("INT models present; Authenticating for SI ")
        else:
            print("No INT models present; hence not authenticating for SI ")

