name: Run Python scripts and store outputs

on: push

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script 1
      id: script1
      run: |
        out=$(python prepare_new_deployment.py)
        versions=$(python new.py "$out")
        echo $envi
        context=$(python deploy.py "$out") 
        echo $context
        models=$(python hs.py "$out") 
        echo $models
        # python host.py "$envi" "$context" "$models"
        # length=${#models[@]}
        
        if [[ ${#models[@]} -ne ${#versions[@]} ]]; then
           echo "equal"
        else
           for (( i=0; i<${#models[@]}; i++ ));do
             echo "{models[$i]}"
             echo "{versions[$i]}"
           done
        fi

      

        fi
