name: Run Python scripts and store outputs

on: push

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script 1
      id: script1
      run: |
        out=$(python prepare_new_deployment.py)
        echo $out
        version=$(python new.py "$out")
        echo $version
        # context=$(python deploy.py "$out") 
        # echo $context
        model=$(python hs.py "$out") 
        echo $model
        # python host.py "$envi" "$context" "$models"
        model=$(tr -d '[]' <<< "$model")
        IFS=',' read -r -a models <<< "$model"
        version=$(tr -d '[]' <<< "$version")
        IFS=',' read -r -a versions <<< "$version"
        length=${#models[@]}
        
        if [[ ${#models[@]} -ne ${#versions[@]} ]]; then
           echo "equal"
        else
           for (( i=0; i<length; i++ ));do
              modelname="${models[$i]//\'/}"
              version"${versions[$i]//\'/}"
              echo $modelname
              echo $version
           done
        fi

      

        
