name: Run Python scripts and store outputs

on: push

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script 1
      id: script1
      run: |
        out=$(python prepare_new_deployment.py)
        context=$(python new.py "$out")
        echo $context
        