name: Store lists in GitHub env

on:
  push:
    branches:
      - main

jobs:
  store_lists:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Python script
        run: |
          python prepare_new_deployment.py > output.txt
          OUTPUT=$(cat output.txt | tr '\n' ' ' | sed 's/\"/\\\"/g')
          ENVIRONMENT=$(echo $OUTPUT | jq -r '.ENVIRONMENT | join(",")')
          DEPLOYMENT_CONTEXT=$(echo $OUTPUT | jq -r '.DEPLOYMENT_CONTEXT | join(",")')
          MODEL_NAMES=$(echo $OUTPUT | jq -r '.MODEL_NAMES | join(",")')
          MODEL_VERSIONS=$(echo $OUTPUT | jq -r '.MODEL_VERSIONS | join(",")')
          SYSTEM_UIDS=$(echo $OUTPUT | jq -r '.SYSTEM_UIDS | join(",")')
          TESTING_TIMES=$(echo $OUTPUT | jq -r '.TESTING_TIMES | join(",")')
          echo "ENVIRONMENT=${ENVIRONMENT}" >> $GITHUB_ENV
          echo "DEPLOYMENT_CONTEXT=${DEPLOYMENT_CONTEXT}" >> $GITHUB_ENV
          echo "MODEL_NAMES=${MODEL_NAMES}" >> $GITHUB_ENV
          echo "MODEL_VERSIONS=${MODEL_VERSIONS}" >> $GITHUB_ENV
          echo "SYSTEM_UIDS=${SYSTEM_UIDS}" >> $GITHUB_ENV
          echo "TESTING_TIMES=${TESTING_TIMES}" >> $GITHUB_ENV
