name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Prepare deployment
      run: python3 deployment.py
      id: prepare_deploy
      continue-on-error: true

    - name: Parse deployment info
      run: |
        env=()
        context=()
        model=()
        version=()
        sysuid=()
        testingtime=()

        while IFS= read -r line; do
          parts=($(echo "$line" | tr '=' ' '))
          env+=("${parts[0]}")
          context+=("${parts[1]}")
          model+=("${parts[2]}")
          version+=("${parts[3]}")
          sysuid+=("${parts[4]}")
          testingtime+=("${parts[5]}")
        done < <(echo "${{ steps.prepare_deploy.outputs.stdout }}")

        echo "Env: ${env[@]}"
        echo "Deployment Context: ${context[@]}"
        echo "Model Names: ${model[@]}"
        echo "Model Versions: ${version[@]}"
        echo "SystemUIDs: ${sysuid[@]}"
        echo "TestingTime: ${testingtime[@]}"
