name: My Workflow

on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Environment Variables
      run: |
        output=$(python3 prepare_re_deployment.py)
        while read -r line; do
          IFS="=" read -r -a parts <<< "$line"
          case ${parts[0]} in
            "SI QA")
              echo "ENV=${parts[0]}" >> $GITHUB_ENV
              echo "DEPLOYMENT_CONTEXT=${parts[1]}" >> $GITHUB_ENV
              echo "MODEL_NAMES=${parts[2]}" >> $GITHUB_ENV
              echo "MODEL_VERSIONS=${parts[3]}" >> $GITHUB_ENV
              echo "SYSTEM_UIDS=${parts[4]}" >> $GITHUB_ENV
              echo "TESTING_TIME=${parts[5]}" >> $GITHUB_ENV
              ;;
            # Add other cases here for different environments
            *)
              ;;
          esac
        done <<< "$output"

    - name: Use Environment Variables
      run: |
        echo $ENV
        echo $DEPLOYMENT_CONTEXT
        echo $MODEL_NAMES
        echo $MODEL_VERSIONS
        echo $SYSTEM_UIDS
        echo $TESTING_TIME
