name: Python Script

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Example Step
        shell: bash
        run: |
          output=$(python prepare_new_deployment.py)
          # Parse output and set environment variables
          ENVIRONMENT=$(echo "$output" | grep -oP "(?<=ENVironment: ).*?(?=\])" | tr -d "[]" | sed "s/'//g" | sed "s/,/ /g")
          DEPLOYMENT_CONTEXT=$(echo "$output" | grep -oP "(?<=DEPLOYMENT_CONTEXT: ).*?(?=\])" | tr -d "[]" | sed "s/'//g" | sed "s/,/ /g")
          MODEL_NAMES=$(echo "$output" | grep -oP "(?<=MODEL_NAMES: ).*?(?=\])" | tr -d "[]" | sed "s/'//g" | sed "s/,/ /g")
          MODEL_VERSIONS=$(echo "$output" | grep -oP "(?<=MODEL_VERSIONS: ).*?(?=\])" | tr -d "[]" | sed "s/'//g" | sed "s/,/ /g")
          SYSTEM_UIDS=$(echo "$output" | grep -oP "(?<=SYSTEM_UIDS: ).*?(?=\])" | tr -d "[]" | sed "s/'//g" | sed "s/,/ /g")
          TESTING_TIMES=$(echo "$output" | grep -oP "(?<=TESTING_TIMES: ).*?(?=\])" | tr -d "[]" | sed "s/'//g" | sed "s/,/ /g")
          
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
          echo "DEPLOYMENT_CONTEXT=$DEPLOYMENT_CONTEXT" >> $GITHUB_ENV
          echo "MODEL_NAMES=$MODEL_NAMES" >> $GITHUB_ENV
          echo "MODEL_VERSIONS=$MODEL_VERSIONS" >> $GITHUB_ENV
          echo "SYSTEM_UIDS=$SYSTEM_UIDS" >> $GITHUB_ENV
          echo "TESTING_TIMES=$TESTING_TIMES" >> $GITHUB_ENV
      - name: Run Python script
        env:
          context: ${{ env.DEPLOYMENT_CONTEXT}}
          models: ${{ env.MODEL_NAMES}}
          versions: ${{ env.MODEL_VERSIONS}}
        run: |
          #python script.py $context $models
          #length=${#models[@]}
              for model in "${models[@]}" 
              do
                    echo "--------------------------------Model:$model[@]-----------------------------------------"
             done
      
        
