name: Store Python Output as Github Environment Variables

on:
  push:
    branches:
      - main

jobs:
  store_output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Python script
        run: python prepare_new_deployment.py > output.txt

      - name: Read output file
        run: |
          env_str=$(cat output.txt)
          echo "Output string: $env_str"

      - name: Set environment variables
        run: |
          IFS=',' read -ra env_arr <<< "$env_str"
          values = env_str.split(",")

          ENVironment = values[0].strip("[]'")
          Envi = values[1].strip("[]'")
          DEPLOYMENT_CONTEXT = values[2].strip("[]'")
          MODEL_NAMES = values[3].strip("[]'")
          MODEL_VERSIONS = values[4].strip("[]'")
          SYSTEM_UIDS = values[5].strip("[]'")
          TESTING_TIMES = values[6].strip("[]'")
          host = values[7].strip()

          echo "ENVironment=${ENVironment}" >> $GITHUB_ENV
          echo "Envi=${Envi}" >> $GITHUB_ENV
          echo "DEPLOYMENT_CONTEXT=${DEPLOYMENT_CONTEXT}" >> $GITHUB_ENV
          echo "MODEL_NAMES=${MODEL_NAMES}" >> $GITHUB_ENV
          echo "MODEL_VERSIONS=${MODEL_VERSIONS}" >> $GITHUB_ENV
          echo "SYSTEM_UIDS=${SYSTEM_UIDS}" >> $GITHUB_ENV
          echo "TESTING_TIMES=${TESTING_TIMES}" >> $GITHUB_ENV
          echo "host=${host}" >> $GITHUB_ENV
          
      - name: Print environment variables
        run: |
          echo "ENVironment: $ENVironment"
          echo "Envi: $Envi"
          echo "DEPLOYMENT_CONTEXT: $DEPLOYMENT_CONTEXT"
          echo "MODEL_NAMES: $MODEL_NAMES"
          echo "MODEL_VERSIONS: $MODEL_VERSIONS"
          echo "SYSTEM_UIDS: $SYSTEM_UIDS"
          echo "TESTING_TIMES: $TESTING_TIMES"
          echo "host: $host"
      
    # - name: authunticate
    #   run: |
    #     output=$(python prepare_new_deployment.py)
    #     ENVironment=$(cut -d '=' -f1 <<< "$output")
    #     echo $ENVironment

    #     if [[ $ENVironment =~ "INT" ]]; then
    #       echo "INT models present; Authenticating for SI"
    #       # Add authentication steps for SI INT
    #     else
    #       echo "No INT models present; hence not authenticating for SI"
    #     fi

    #     if [[ $ENVironment =~ "QA" ]]; then
    #       echo "QA models present; Authenticating for SI"
    #       # Add authentication steps for SI QA
    #     else
    #       echo "No QA models present; hence not authenticating for SI"
    #     fi

    #     if [[ $ENVironment =~ "PROD" ]]; then
    #       echo "PROD models present; Authenticating for SI"
    #       # Add authentication steps for SI PROD
    #     else
    #       echo "No PROD models present; hence not authenticating for SI"
    #     fi

    # - name: Verify environment variables
    #   run: |
    #     output=$(python prepare_new_deployment.py)
    #     ENVironment=$(cut -d '=' -f1 <<< "$output")
    #     context=$(cut -d '=' -f2 <<< "$output")
    #     models=$(cut -d '=' -f3 <<< "$output")
    #     # echo $ENVironment
    #     # echo $context
    #     # echo $models
    #     python host.py "$ENVironment" "$context" "$models"


    # - name: Verify environment variables
    #   run: |
    #     # echo "ENVironment=$ENVironment"
    #     #echo "MODEL_NAMES=$MODEL_NAMES"
    #     #echo "MODEL_VERSIONS=$MODEL_VERSIONS"
    #     echo "DEPLOYMENT_CONTEXT=$DEPLOYMENT_CONTEXT"
    #     #echo "SYSTEM_UIDS=$SYSTEM_UIDS"
    #     #echo "TESTING_TIMES=$TESTING_TIMES"
    # - name: Run script
    #   run: |


    #     if [[ $ENVironment =~ "INT" ]]; then
    #       echo "INT models present; Authenticating for SI"
    #       # Add authentication steps for SI INT
    #     else
    #       echo "No INT models present; hence not authenticating for SI"
    #     fi

    #     if [[ $ENVironment =~ "QA" ]]; then
    #       echo "QA models present; Authenticating for SI"
    #       # Add authentication steps for SI QA
    #     else
    #       echo "No QA models present; hence not authenticating for SI"
    #     fi

    #     if [[ $ENVironment =~ "PROD" ]]; then
    #       echo "PROD models present; Authenticating for SI"
    #       # Add authentication steps for SI PROD
    #     else
    #       echo "No PROD models present; hence not authenticating for SI"
    #     fi
    #   env:
    #     ENVironment: ${{ env.ENVironment }}
    # - name: Deploy to environment
    #   env:
    #     ENVironment: ${{ env.ENVironment }}
    #   run: |
    #       for i in "${!ENVironment[@]}"; do
    #         parts=(${ENVironment[$i]// / })
    #         case "${parts[1]}" in
    #           INT)
    #             HOST="hsi7.com"
    #             ;;
    #           QA)
    #             HOST="3.com"
    #             ;;
    #           PROD)
    #             HOST="5.com"
    #             ;;
    #         esac
    #         echo "Deploying to ${parts[1]} environment on host ${HOST}"
    #         # Add your deployment commands here using $HOST
    #       done



