name: example_workflow

on:
  push:
    branches: [main]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set environment variables
        run: |
          output=$(python3 deployment.py)
          env=$(echo "$output" | awk -F'=' '/^env/ {print $2}')
          context=$(echo "$output" | awk -F'=' '/^context/ {print $2}')
          model=$(echo "$output" | awk -F'=' '/^model/ {print $2}')
          version=$(echo "$output" | awk -F'=' '/^version/ {print $2}')
          sysuid=$(echo "$output" | awk -F'=' '/^sysuid/ {print $2}')
          testingtime=$(echo "$output" | awk -F'=' '/^testingtime/ {print $2}')

          echo "Setting environment variables"
          echo "ENV=$env" >> $GITHUB_ENV
          echo "CONTEXT=$context" >> $GITHUB_ENV
          echo "MODEL=$model" >> $GITHUB_ENV
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "SYSUID=$sysuid" >> $GITHUB_ENV
          echo "TESTINGTIME=$testingtime" >> $GITHUB_ENV

      - name: Use environment variables
        run: |
          echo "Env: $ENV"
          echo "Deployment Context: $CONTEXT"
          echo "Model Names: $MODEL"
          echo "Model Versions: $VERSION"
          echo "SystemUIDs: $SYSUID"
          echo "TestingTime: $TESTINGTIME"
