name: Set Environment Variables

on:
  push:
    branches:
      - main

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Python script
      run: |
        output=$(python prepare_new_deployment.py)
        echo "$output"
        # Parse the output and set the environment variables
        model_names=$(echo "$output" | grep -oP "(?<=MODEL_NAMES: )\['.*?'\]" | tr -d '[],'"'"'')
        echo "MODEL_NAMES=$model_names" >> $GITHUB_ENV

        model_versions=$(echo "$output" | grep -oP "(?<=MODEL_VERSIONS: )\['.*?'\]" | tr -d '[],'"'"'')
        echo "MODEL_VERSIONS=$model_versions" >> $GITHUB_ENV

        deployment_contexts=$(echo "$output" | grep -oP "(?<=DEPLOYMENT_CONTEXT: )\['.*?'\]" | tr -d '[],'"'"'')
        echo "DEPLOYMENT_CONTEXT=$deployment_contexts" >> $GITHUB_ENV

        system_uids=$(echo "$output" | grep -oP "(?<=SYSTEM_UIDS: )\['.*?'\]" | tr -d '[],'"'"'')
        echo "SYSTEM_UIDS=$system_uids" >> $GITHUB_ENV

        testing_times=$(echo "$output" | grep -oP "(?<=TESTING_TIMES: )\['.*?'\]" | tr -d '[],'"'"'')
        echo "TESTING_TIMES=$testing_times" >> $GITHUB_ENV

    - name: Verify environment variables
      run: |
        echo "MODEL_NAMES=$MODEL_NAMES"
        echo "MODEL_VERSIONS=$MODEL_VERSIONS"
        echo "DEPLOYMENT_CONTEXT=$DEPLOYMENT_CONTEXT"
        echo "SYSTEM_UIDS=$SYSTEM_UIDS"
        echo "TESTING_TIMES=$TESTING_TIMES"
