name: Prepare RE Deployment
on:
  push:
    branches: [ main ]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Python script
      run: |
        python3 deployment.py
        export Text=$(python3 deployment.py)

        envi=()
        context=()
        model=()
        version=()
        sysuid=()
        testingtime=()

        for i in $(echo "$Text" | awk '{print $0}'); do
          IFS='=' read -ra parts <<< "$i"
          case "${parts[0]}" in
            "env")
              env+=("${parts[1]}")
              ;;
            "context")
              context+=("${parts[1]}")
              ;;
            "model")
              model+=("${parts[1]}")
              ;;
            "version")
              version+=("${parts[1]}")
              ;;
            "sysuid")
              sysuid+=("${parts[1]}")
              ;;
            "testingtime")
              testingtime+=("${parts[1]}")
              ;;
          esac
        done

        echo "::set-output name=env::${env[@]}"
        echo "::set-output name=context::${context[@]}"
        echo "::set-output name=model::${model[@]}"
        echo "::set-output name=version::${version[@]}"
        echo "::set-output name=sysuid::${sysuid[@]}"
        echo "::set-output name=testingtime::${testingtime[@]}"

    - name: Print values
      run: |
        echo "Env: ${{ env }}"
        echo "Deployment Context: ${{ context }}"
        echo "Model Names: ${{ model }}"
        echo "Model Versions: ${{ version }}"
        echo "SystemUIDs: ${{ sysuid }}"
        echo "TestingTime: ${{ testingtime }}"
