name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run Python script and store output
      run: |
        python my_script.py > output.txt
        output=$(cat output.txt)
        IFS=',' read var1 var2 var3 var4 var5 <<< "$output"
      
    - name: Set environment variables
      run: |
        echo "VAR1=$var1" >> $GITHUB_ENV
        echo "VAR2=$var2" >> $GITHUB_ENV
        echo "VAR3=$var3" >> $GITHUB_ENV
	  echo "VAR4=$var4" >> $GITHUB_ENV
        echo "VAR5=$var5" >> $GITHUB_ENV
    - name: Use environment variables
      run: |
        echo "VAR1=$VAR1"
        echo "VAR2=$VAR2"
        echo "VAR3=$VAR3"
        echo "VAR4=$VAR4"
        echo "VAR5=$VAR5"
