name: Store Python script output to GitHub env

on:
  push:
    branches: [main]

jobs:
  store-env:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run Python script and store output in env variables
      run: |
        output=$(python prepare_new_deployment.py)
        echo "ENVironment=${output[0]}" >> $GITHUB_ENV
        echo "DEPLOYMENT_CONTEXT=${output[1]}" >> $GITHUB_ENV
        echo "MODEL_NAMES=${output[2]}" >> $GITHUB_ENV
        echo "MODEL_VERSIONS=${output[3]}" >> $GITHUB_ENV
        echo "SYSTEM_UIDS=${output[4]}" >> $GITHUB_ENV
        echo "TESTING_TIMES=${output[5]}" >> $GITHUB_ENV
        
    - name: Check env variables
      run: |
        echo "ENVironment: ${{ env.ENVironment }}"
        echo "DEPLOYMENT_CONTEXT: ${{ env.DEPLOYMENT_CONTEXT }}"
        echo "MODEL_NAMES: ${{ env.MODEL_NAMES }}"
        echo "MODEL_VERSIONS: ${{ env.MODEL_VERSIONS }}"
        echo "SYSTEM_UIDS: ${{ env.SYSTEM_UIDS }}"
        echo "TESTING_TIMES: ${{ env.TESTING_TIMES }}"
