name: example_workflow

on:
  push:
    branches: [main]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set environment variables
        run: |
          output=$(python3 deployment.py)
          envi=$(echo "$output" | awk -F'=' '/^env/ {print $2}')
          context=$(echo "$output" | awk -F'=' '/^context/ {print $2}')
          model=$(echo "$output" | awk -F'=' '/^model/ {print $2}')
          version=$(echo "$output" | awk -F'=' '/^version/ {print $2}')
          sysuid=$(echo "$output" | awk -F'=' '/^sysuid/ {print $2}')
          testingtime=$(echo "$output" | awk -F'=' '/^testingtime/ {print $2}')
          echo "::set-output name=ENVI::${envi}"
          echo "::set-output name=CONTEXT::${context}"
          echo "::set-output name=MODEL::${model}"
          echo "::set-output name=VERSION::${version}"
          echo "::set-output name=SYSUID::${sysuid}"
          echo "::set-output name=TESTINGTIME::${testingtime}"
          # echo "Setting environment variables"
          # echo "ENV=$env" >> $GITHUB_ENV
          # echo "CONTEXT=$context" >> $GITHUB_ENV
          # echo "MODEL=$model" >> $GITHUB_ENV
          # echo "VERSION=$version" >> $GITHUB_ENV
          # echo "SYSUID=$sysuid" >> $GITHUB_ENV
          # echo "TESTINGTIME=$testingtime" >> $GITHUB_ENV
      - name: Print environment variables
        run: |
          echo "Envi: $ENVI"
          echo "Deployment Context: $CONTEXT"
          echo "Model Names: $MODEL"
          echo "Model Versions: $VERSION"
          echo "SystemUIDs: $SYSUID"
          echo "TestingTime: $TESTINGTIME"
