name: My Workflow

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run prepare_re_deployment.py
        run: |
          output=$(python3 prepare_re_deployment.py)
          env=()
          context=()
          model=()
          version=()
          sysuid=()
          testingtime=()

          while read -r line; do
            IFS='=' read -ra parts <<< "$line"
            for i in "${!parts[@]}"; do
              case "$i" in
                0) export env+=("${parts[i]}") ;;
                1) export context+=("${parts[i]}") ;;
                2) export model+=("${parts[i]}") ;;
                3) export version+=("${parts[i]}") ;;
                4) export sysuid+=("${parts[i]}") ;;
                5) export testingtime+=("${parts[i]}") ;;
              esac
            done
          done <<< "$output"

          echo "Env: ${env[@]}"
          echo "Deployment Context: ${context[@]}"
          echo "Model Names: ${model[@]}"
          echo "Model Versions: ${version[@]}"
          echo "SystemUIDs: ${sysuid[@]}"
          echo "TestingTime: ${testingtime[@]}"
