name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Python script and store output
      run: |
        python my_script.py > output.txt
        output=$(cat output.txt)
        IFS=$'\n' readarray -t lines <<< "$output"
        IFS=',' read MODES <<< "${lines[0]}"
        IFS=',' read VERSIONS <<< "${lines[1]}"
        IFS=',' read ENVIRS <<< "${lines[2]}"
        echo "MODES=$MODES" >> $GITHUB_ENV
        echo "VERSIONS=$VERSIONS" >> $GITHUB_ENV
        echo "ENVIRS=$ENVIRS" >> $GITHUB_ENV
      
    - name: Use environment variables
      run: |
        echo "MODES=$MODES"
        echo "VERSIONS=$VERSIONS"
        echo "ENVIRS=$ENVIRS"
    - name: SI authentication
      run: |
        if [[ "$ENVIRS" == *"abc QA"* ]]; then
           echo "QA models present; hence not authenticating for SI 7"
        else
           echo "No QA models present; hence not authenticating for SI 7"
        fi
