name: Python Script

on: [push]

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # - name: Setup Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.x'
      - name: Run script
        run: |
          # Run your Python script and store its output in a list
          output=$(python your_script.py)
          # Separate the list values and store them in separate environment variables
          IFS=' ' read -ra values <<< "$output"
          echo "ENVironment=${values[0]}" >> $GITHUB_ENV
          echo "DEPLOYMENT_CONTEXT=${values[1]}" >> $GITHUB_ENV
          echo "MODEL_NAMES=${values[2]}" >> $GITHUB_ENV
          echo "MODEL_VERSIONS=${values[3]}" >> $GITHUB_ENV
          echo "SYSTEM_UIDS=${values[4]}" >> $GITHUB_ENV
          echo "TESTING_TIMES=${values[5]}" >> $GITHUB_ENV
