name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Prepare deployment
      run: python3 prepare_re_deployment.py
      id: prepare_deploy
      continue-on-error: true

    - name: Parse deployment info
      run: |
        env=()
        context=()
        model=()
        version=()
        sysuid=()
        testingtime=()

        echo "Running the prepare_re_deployment.py script..."
        sh "python3 practice/prepare_re_deployment.py"

        echo "Reading output from the prepare_re_deployment.py script..."
        Text=$(python3 prepare_re_deployment.py)
        echo "Text: ${Text}"

        echo "Parsing the output and storing the values..."
        for line in ${Text[@]}; do
          echo "Parsing line: ${line}"
          IFS='=' read -ra parts <<< "${line}"
          for idx in "${!parts[@]}"; do
            echo "Parsing part[${idx}]: ${parts[$idx]}"
            case $idx in            
              0) 
                env+=("${parts[$idx]}")
                ;;
              1) 
                context+=("${parts[$idx]}")
                ;;
              2) 
                model+=("${parts[$idx]}")
                ;;
              3)
                version+=("${parts[$idx]}")
                ;;
              4)
                sysuid+=("${parts[$idx]}")
                ;;
              5)
                testingtime+=("${parts[$idx]}")
                ;;
            esac
          done
        done

        echo "Env: ${env[@]}"
        echo "Deployment Context: ${context[@]}"
        echo "Model Names: ${model[@]}"
        echo "Model Versions: ${version[@]}"
        echo "SystemUIDs: ${sysuid[@]}"
        echo "TestingTime: ${testingtime[@]}"
