name: My Workflow

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Run prepare_re_deployment.py
        run: |
          set -x
          output=$(python3 prepare_re_deployment.py)
          echo "Output: $output"
          env=()
          context=()
          model=()
          version=()
          sysuid=()
          testingtime=()
          while IFS= read -r line; do
            parts=($line)
            env+=(${parts[0]})
            context+=(${parts[1]})
            model+=(${parts[2]})
            version+=(${parts[3]})
            sysuid+=(${parts[4]})
            testingtime+=(${parts[5]})
          done <<< "$output"
          echo "Env: ${env[@]}"
          echo "Deployment Context: ${context[@]}"
          echo "Model Names: ${model[@]}"
          echo "Model Versions: ${version[@]}"
          echo "SystemUIDs: ${sysuid[@]}"
          echo "TestingTime: ${testingtime[@]}"
      - name: Set output variables
        run: |
          echo "::set-env name=ENV::${env[@]}"
          echo "::set-env name=DEPLOYMENT_CONTEXT::${context[@]}"
          echo "::set-env name=MODEL_NAMES::${model[@]}"
          echo "::set-env name=MODEL_VERSIONS::${version[@]}"
          echo "::set-env name=SYSTEM_UIDS::${sysuid[@]}"
          echo "::set-env name=TESTING_TIME::${testingtime[@]}"
