name: Set Environment Variables

on:
  push:
    branches:
      - main

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Git Sumbodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --init --recursive
        pwd
        ls

    - name: Run Python script
      run: |
        output=$(python prepare_new_deployment.py)
        echo "$output"
        # Parse the output and set the environment variables
        environment=$(echo "$output" | grep -oP "(?<=ENVironment: )\['.*?'\]" | tr -d '[],'"'"'')
        echo "::set-env name=ENVironment::$environment"

        model_names=$(echo "$output" | grep -oP "(?<=MODEL_NAMES: )\['.*?'\]" | tr -d '[],'"'"'')
        echo "::set-env name=MODEL_NAMES::$model_names"

        model_versions=$(echo "$output" | grep -oP "(?<=MODEL_VERSIONS: )\['.*?'\]" | tr -d '[],'"'"'')
        echo "::set-env name=MODEL_VERSIONS::$model_versions"

        deployment_contexts=$(echo "$output" | grep -oP "(?<=DEPLOYMENT_CONTEXT: )\['.*?'\]" | tr -d '[],'"'"'')
        echo "::set-env name=DEPLOYMENT_CONTEXT::$deployment_contexts"

        system_uids=$(echo "$output" | grep -oP "(?<=SYSTEM_UIDS: )\['.*?'\]" | tr -d '[],'"'"'')
        echo "::set-env name=SYSTEM_UIDS::$system_uids"

        testing_times=$(echo "$output" | grep -oP "(?<=TESTING_TIMES: )\['.*?'\]" | tr -d '[],'"'"'')
        echo "::set-env name=TESTING_TIMES::$testing_times"


    - name: Verify environment variables
      run: |
        # echo "ENVironment=$ENVironment"
        #echo "MODEL_NAMES=$MODEL_NAMES"
        #echo "MODEL_VERSIONS=$MODEL_VERSIONS"
        echo "DEPLOYMENT_CONTEXT=$DEPLOYMENT_CONTEXT"
        #echo "SYSTEM_UIDS=$SYSTEM_UIDS"
        #echo "TESTING_TIMES=$TESTING_TIMES"
    - name: Run script
      run: |


        if [[ $ENVironment =~ "INT" ]]; then
          echo "INT models present; Authenticating for SI"
          # Add authentication steps for SI INT
        else
          echo "No INT models present; hence not authenticating for SI"
        fi

        if [[ $ENVironment =~ "QA" ]]; then
          echo "QA models present; Authenticating for SI"
          # Add authentication steps for SI QA
        else
          echo "No QA models present; hence not authenticating for SI"
        fi

        if [[ $ENVironment =~ "PROD" ]]; then
          echo "PROD models present; Authenticating for SI"
          # Add authentication steps for SI PROD
        else
          echo "No PROD models present; hence not authenticating for SI"
        fi
      env:
        ENVironment: ${{ env.ENVironment }}
    - name: Deploy to environment
      env:
        ENVironment: ${{ env.ENVironment }}
      run: |
          for i in "${!ENVironment[@]}"; do
            parts=(${ENVironment[$i]// / })
            case "${parts[1]}" in
              INT)
                HOST="hsi7.com"
                ;;
              QA)
                HOST="3.com"
                ;;
              PROD)
                HOST="5.com"
                ;;
            esac
            echo "Deploying to ${parts[1]} environment on host ${HOST}"
            # Add your deployment commands here using $HOST
          done



