name: example_workflow

on:
  push:
    branches: [main]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run prepare_re_deployment.py
        run: |
- name: Get deployment info
  run: |
    python3 deployment.py
    declare -a env=()
    declare -a context=()
    declare -a model=()
    declare -a version=()
    declare -a sysuid=()
    declare -a testingtime=()

    while read line; do
      arr=(${line//=/ })
      case ${arr[0]} in
        "env") env+=(${arr[1]});;
        "context") context+=(${arr[1]});;
        "model") model+=(${arr[1]});;
        "version") version+=(${arr[1]});;
        "sysuid") sysuid+=(${arr[1]});;
        "testingtime") testingtime+=(${arr[1]});;
      esac
    done < <(python3 prepare_re_deployment.py)
  env:
    env: ${{ env }}
    context: ${{ context }}
    model: ${{ model }}
    version: ${{ version }}
    sysuid: ${{ sysuid }}
    testingtime: ${{ testingtime }}
