name: Python Script

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Example Step
        shell: bash
        run: |
          output=$(python prepare_new_deployment.py)
          # Parse output and set environment variables
          ENVIRONMENT=$(echo "$output" | grep -oP "(?<=ENVironment: ).*?(?=\])" | tr -d "[]" )
          DEPLOYMENT_CONTEXT=$(echo "$output" | grep -oP "(?<=DEPLOYMENT_CONTEXT: ).*?(?=\])" | tr -d "[]" )
          MODEL_NAMES=$(echo "$output" | grep -oP "(?<=MODEL_NAMES: ).*?(?=\])" | tr -d "[]" )
          MODEL_VERSIONS=$(echo "$output" | grep -oP "(?<=MODEL_VERSIONS: ).*?(?=\])" | tr -d "[]" )
          SYSTEM_UIDS=$(echo "$output" | grep -oP "(?<=SYSTEM_UIDS: ).*?(?=\])" | tr -d "[]" )
          TESTING_TIMES=$(echo "$output" | grep -oP "(?<=TESTING_TIMES: ).*?(?=\])" | tr -d "[]" )
    
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
          echo "DEPLOYMENT_CONTEXT=$DEPLOYMENT_CONTEXT" >> $GITHUB_ENV
          echo "MODEL_NAMES=$MODEL_NAMES" >> $GITHUB_ENV
          echo "MODEL_VERSIONS=$MODEL_VERSIONS" >> $GITHUB_ENV
          echo "SYSTEM_UIDS=$SYSTEM_UIDS" >> $GITHUB_ENV
          echo "TESTING_TIMES=$TESTING_TIMES" >> $GITHUB_ENV

      - name: Display Environment Variables
        run: |
            echo "MODEL_NAMES=${{ env.MODEL_NAMES}}"