- name: Get deployment info
  run: |
    # Replace the below command with the command to run your script
    sh "python3 deployment.py"
    # Parse the output of your script
    env=()
    context=()
    model=()
    version=()
    sysuid=()
    testingtime=()
    Text=$(python3 deployment.py)
    IFS=$'\n' # Set the delimiter to newline
    for line in $Text; do
        IFS='=' read -ra parts <<< "$line" # Split each line into parts
        for i in "${!parts[@]}"; do
            case $i in
                0) env+=("${parts[i]}");;
                1) context+=("${parts[i]}");;
                2) model+=("${parts[i]}");;
                3) version+=("${parts[i]}");;
                4) sysuid+=("${parts[i]}");;
                5) testingtime+=("${parts[i]}");;
            esac
        done
    done
    # Print the parsed values for debugging
    echo "Env: ${env[@]}"
    echo "Deployment Context: ${context[@]}"
    echo "Model Names: ${model[@]}"
    echo "Model Versions: ${version[@]}"
    echo "SystemUIDs: ${sysuid[@]}"
    echo "TestingTime: ${testingtime[@]}"
    # Set the environment variables for use in later steps
    echo "::set-output name=DEPLOYMENT_ENV::${env[@]}"
    echo "::set-output name=DEPLOYMENT_CONTEXT::${context[@]}"
    echo "::set-output name=DEPLOYMENT_MODEL::${model[@]}"
    echo "::set-output name=DEPLOYMENT_VERSION::${version[@]}"
    echo "::set-output name=DEPLOYMENT_SYSUID::${sysuid[@]}"
    echo "::set-output name=DEPLOYMENT_TESTING_TIME::${testingtime[@]}"
