name: My Workflow
on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Prepare deployment
      run: |
        sh "python3 deployment.py"
        env=""
        context=""
        model=""
        version=""
        sysuid=""
        testingtime=""
        def Text = sh returnStdout:true, script: "python3 deployment.py"
        for(int i = 0;i<Text.readLines().size();i++) {
          String[] parts = Text.readLines().get(i).split("=")
          for(j =0; j<parts.size();j++){
            switch(j) {            
              case 0: 
                env.add(parts[j])
                break;
              case 1: 
                context.add(parts[j])
                break;
              case 2: 
                model.add(parts[j])  
                break;
              case 3:
                version.add(parts[j])
                break;
              case 4:
                sysuid.add(parts[j])
                break;
              case 5:
                testingtime.add(parts[j])
            }
          }
        }
        print "Env:" + env
        print "Deployment Context:" + context
        print "Model Names:" + model
        print "Model Versions:" + version 
        print "SystemUIDs:" +  sysuid
        print "TestingTime:" + testingtime   

        if(env.contains("SI INT")){
          print("INT models present; Authenticating for SI ")
        }
        else {
          print("No INT models present; hence not authenticating for SI ")
        }

        if(env.contains("SI QA")){
          print("INT models present; Authenticating for SI ")
        }
        else {
          print("No INT models present; hence not authenticating for SI ")
        }

        if(env.contains("SI PROD)){
          print("INT models present; Authenticating for SI ")
        }
        else {
          print("No INT models present; hence not authenticating for SI ")
        }
