name: example_workflow

on:
  push:
    branches: [main]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run prepare_re_deployment.py
        run: |
          env=()
          context=()
          model=()
          version=()
          sysuid=()
          testingtime=()
          sh "python3 prepare_re_deployment.py"
          while read line; do
            parts=(${line//=/ })
            case ${parts[0]} in
              "Env:") env+=("${parts[1]}");;
              "Deployment Context:") context+=("${parts[1]}");;
              "Model Names:") model+=("${parts[1]}");;
              "Model Versions:") version+=("${parts[1]}");;
              "SystemUIDs:") sysuid+=("${parts[1]}");;
              "TestingTime:") testingtime+=("${parts[1]}");;
            esac
          done < output.txt
          
      - name: Print arrays
        run: |
          echo "Env: ${env[@]}"
          echo "Deployment Context: ${context[@]}"
          echo "Model Names: ${model[@]}"
          echo "Model Versions: ${version[@]}"
          echo "SystemUIDs: ${sysuid[@]}"
          echo "TestingTime: ${testingtime[@]}"
        
      - name: Set env variables
        env:
          ENV: "${env[@]}"
          CONTEXT: "${context[@]}"
          MODEL: "${model[@]}"
          VERSION: "${version[@]}"
          SYSUID: "${sysuid[@]}"
          TESTINGTIME: "${testingtime[@]}"