name: Read YAML file and set env vars

on:
  push:
    branches:
      - main

jobs:
  read-yaml-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install jq and envfile
        run: |
          sudo apt-get install -y jq
          curl -sSL https://github.com/alexkasko/envfile/releases/download/v1.2.0/envfile_linux_amd64 -o envfile
          chmod +x envfile

      - name: Read YAML file and set env vars
        run: |
          # Read the YAML file and extract the desired values
          DEPLOYMENT_CONTEXT=$(cat model_detailsdeployment.yml | jq -r '.[].DeploymentContext')
          MODEL_NAME=$(cat model_detailsdeployment.yml | jq -r '.[].ModelName')
          MODEL_VERSION=$(cat model_detailsdeployment.yml | jq -r '.[].ModelVersion')
          
          # Write the values to a temporary file
          echo "DEPLOYMENT_CONTEXT=$DEPLOYMENT_CONTEXT" > tmp_envfile
          echo "MODEL_NAME=$MODEL_NAME" >> tmp_envfile
          echo "MODEL_VERSION=$MODEL_VERSION" >> tmp_envfile
          
          # Load the temporary file into GitHub environment variables
          ./envfile tmp_envfile

          # Print the values to verify
          echo "DEPLOYMENT_CONTEXT=$DEPLOYMENT_CONTEXT"
          echo "MODEL_NAME=$MODEL_NAME"
          echo "MODEL_VERSION=$MODEL_VERSION"
