name: Deployment Workflow
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Setup Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.x'

      # - name: Install dependencies
      #   run: pip3 install -r requirements.txt

      - name: Prepare for Deployment
        run: |
          python3 deployment.py
          TEXT=$(python3 deployment.py)
          echo "$TEXT" | while read line; do
            IFS='=' read -ra PARTS <<< "$line"
            for j in "${!PARTS[@]}"; do
              case $j in
                0) env=${PARTS[$j]};;
                1) context=${PARTS[$j]};;
                2) model=${PARTS[$j]};;
                3) version=${PARTS[$j]};;
                4) sysuid=${PARTS[$j]};;
                5) testingtime=${PARTS[$j]};;
              esac
            done
            echo "Env: $env"
            echo "Deployment Context: $context"
            echo "Model Names: $model"
            echo "Model Versions: $version"
            echo "SystemUIDs: $sysuid"
            echo "TestingTime: $testingtime"
          done

      - name: Authenticate for SI INT
        run: |
          if [[ "$env" == *"SI INT"* ]]; then
            echo "INT models present; Authenticating for SI"
          else
            echo "No INT models present; hence not authenticating for SI"
          fi

      - name: Authenticate for SI QA
        run: |
          if [[ "$env" == *"SI QA"* ]]; then
            echo "QA models present; Authenticating for SI"
          else
            echo "No QA models present; hence not authenticating for SI"
          fi

      - name: Authenticate for SI PROD
        run: |
          if [[ "$env" == *"SI PROD"* ]]; then
            echo "PROD models present; Authenticating for SI"
          else
            echo "No PROD models present; hence not authenticating for SI"
          fi
