name: Update Secrets

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'



    - name: Set up AdoptOpenJDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'maven'
        maven-version: '3.8.4'

    - name: Verify Maven version
      run: mvn -v
    - name: python
      run: python -m pip install pyyaml
    - name: copy file
      run: cp test.yaml test1.template.yaml

    - name: Run Python script to update secrets
      env:
        iam_name: ${{ secrets.iam_name }}
        iam_pass: ${{ secrets.iam_pass }}
        db_name: ${{ secrets.db_name }}
        db_pass: ${{ secrets.db_pass }}
      run: python update_secrets.py

    - name: Commit updated test1.yaml
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add test1.yaml
        git commit -m 'Update test1.yaml with secrets'
        git push
